name: projectGNN
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - requests
  - matplotlib
  - scipy
  - pytorch
  - pip=23.2.1
  - tqdm
  - scikit-learn
  - pip:
    - torch-geometric
    - torch-geometric-temporal